# Generated by Django 4.2.7 on 2025-11-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='generation',
            field=models.CharField(blank=True, help_text='Например: JZX90, E46, W210 и т.д.', max_length=100, null=True, verbose_name='Поколение/Кузов'),
        ),
    ]
