# Generated by Django 4.2.7 on 2025-11-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_car_generation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['user', '-created_at'], name='car_user_created_idx'),
        ),
    ]
