# Generated by Django 4.2.7 on 2025-11-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_car_car_user_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фото будет автоматически обрезано до прямоугольного формата', null=True, upload_to='cars/%Y/%m/%d/', verbose_name='Фото автомобиля'),
        ),
    ]
