# Generated by Django 4.2.7 on 2025-11-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Госномер'),
        ),
    ]
