# Generated by Django 4.2.7 on 2025-11-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_car_license_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='cars/photos/%Y/%m/%d/', verbose_name='Фото')),
                ('is_primary', models.BooleanField(default=False, help_text='Основное фото отображается на карточке автомобиля', verbose_name='Основное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фото автомобиля',
                'verbose_name_plural': 'Фото автомобилей',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['car', '-is_primary', '-created_at'], name='car_photo_idx')],
            },
        ),
    ]
