# Generated by Django 4.2.7 on 2025-11-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_badge_user_is_anonymous_userbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_anonymous',
        ),
    ]
