# Generated by Django 4.2.7 on 2025-11-18 23:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('stputyxa', 'Stputyxa'), ('gohard', 'GO HARD')], default='stputyxa', max_length=50, verbose_name='Бренд/Магазин'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, default=dict, verbose_name='Характеристики (JSON)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_clothing',
            field=models.BooleanField(default=False, verbose_name='Является одеждой'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sticker', 'Наклейка'), ('clothing', 'Одежда'), ('accessory', 'Аксессуар'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип товара'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет (HEX)')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наценка/скидка')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товаров',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
