# Generated by Django 4.2.7 on 2025-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_brand_product_characteristics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название магазина (необязательно)')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL-адрес (slug, автозаполнение)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание (необязательно)')),
                ('logo', models.ImageField(upload_to='shops/logos/%Y/%m/%d/', verbose_name='Логотип')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['order', 'name'],
            },
        ),
    ]
