# Generated by Django 4.2.7 on 2025-11-13 15:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('discount_percent', models.IntegerField(default=0, help_text='Скидка в процентах (0 если используется фиксированная сумма)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Фиксированная скидка в рублях (0 если используется процент)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка (руб.)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма заказа')),
                ('max_uses', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум использований')),
                ('used_count', models.IntegerField(default=0, verbose_name='Количество использований')),
                ('valid_from', models.DateTimeField(verbose_name='Действителен с')),
                ('valid_until', models.DateTimeField(verbose_name='Действителен до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points_per_rub', models.DecimalField(decimal_places=2, default=1.0, help_text='Баллов за 1 рубль покупки', max_digits=5, verbose_name='Баллов за рубль')),
                ('bonus_points_to_rub', models.DecimalField(decimal_places=2, default=100.0, help_text='Сколько рублей за 1 балл (для расчета скидки)', max_digits=5, verbose_name='Рублей за балл')),
                ('booking_advance_days', models.IntegerField(default=30, help_text='На сколько дней вперед можно бронировать', verbose_name='Дней вперед для бронирования')),
                ('working_hours_start', models.TimeField(default='09:00', verbose_name='Начало рабочего дня')),
                ('working_hours_end', models.TimeField(default='18:00', verbose_name='Конец рабочего дня')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Количество баллов')),
                ('transaction_type', models.CharField(choices=[('earned', 'Начислено'), ('spent', 'Потрачено'), ('expired', 'Истекло'), ('manual', 'Ручное начисление/списание')], max_length=20, verbose_name='Тип транзакции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_transactions', to='bookings.booking', verbose_name='Заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция бонусов',
                'verbose_name_plural': 'Транзакции бонусов',
                'ordering': ['-created_at'],
            },
        ),
    ]
