# Generated by Django 4.2.7 on 2025-11-13 15:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории форума (например: "Тюнинг", "Запчасти")', max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Краткое описание категории', null=True, verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для URL (например: tuning, parts)', unique=True, verbose_name='URL-адрес')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения категории в списке (меньше = выше)', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображается ли категория на сайте', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория форума',
                'verbose_name_plural': 'Категории форума',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок темы (минимум 5 символов)', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Текст темы (минимум 10 символов)', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Содержание')),
                ('is_pinned', models.BooleanField(default=False, help_text='Закреплена ли тема в верхней части списка', verbose_name='Закреплена')),
                ('is_locked', models.BooleanField(default=False, help_text='Закрыта ли тема для новых сообщений', verbose_name='Закрыта')),
                ('views_count', models.IntegerField(default=0, help_text='Сколько раз тему просмотрели', verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(help_text='Пользователь, создавший тему', on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(help_text='Категория, к которой относится тема', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.forumcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тема форума',
                'verbose_name_plural': 'Темы форума',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Текст сообщения', validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Содержание')),
                ('is_edited', models.BooleanField(default=False, help_text='Было ли сообщение отредактировано', verbose_name='Отредактировано')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(help_text='Пользователь, написавший сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('topic', models.ForeignKey(help_text='Тема, к которой относится сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.forumtopic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Сообщение форума',
                'verbose_name_plural': 'Сообщения форума',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('post', models.ForeignKey(help_text='Сообщение, которому поставили лайк', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.forumpost', verbose_name='Сообщение')),
                ('user', models.ForeignKey(help_text='Пользователь, поставивший лайк', on_delete=django.db.models.deletion.CASCADE, related_name='forum_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['category', '-created_at'], name='forum_forum_categor_820230_idx'),
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['author', '-created_at'], name='forum_forum_author__4b681f_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['topic', 'created_at'], name='forum_forum_topic_i_66b449_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author', '-created_at'], name='forum_forum_author__e19f06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumlike',
            unique_together={('post', 'user')},
        ),
    ]
